sudo: false
language: node_js

env:
  - SENECA_VER=seneca@3.x.x
  - SENECA_VER=seneca@plugin
  - SENECA_VER=senecajs/seneca
  - NODE_VERSION=$(node -v)
  
node_js:
  - "10"
  - "8"
  - "6"
  - "4"


install:
  - if [ ${NODE_VERSION:1:2} -ge 10 ]; then npm i -g npm@6; npm ci; else npm install; fi

script:
  - npm test
  - if [ ${NODE_VERSION:1:2} -ge 10 ]; then npm audit; fi

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
