language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'

# to kill when droping 0.10
before_install:
   - npm -g install npm@latest-2

before_script:
   - npm install seneca$SENECA_VER
